# Generated by Django 5.2.5 on 2025-08-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('appetizers and snack', 'APPETIZERS AND SNACK'), ('main dishes', 'MAIN DISHES'), ('bread and blaked goods', 'BREAD AND BLAKED GOODS'), ('desserts', 'DESSERTS'), ('salads and slides', 'SALADS AND SLIDES'), ('soups and stews', 'SOUPS AND STEWS'), ('not specified', 'NOT SPECIFIED')], max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
