# Generated by Django 5.2.5 on 2025-08-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='recipe.recipemodel')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
