# Generated by Django 5.2.5 on 2025-08-09 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_instructionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngrediantsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediants', to='recipe.recipemodel')),
            ],
        ),
    ]
