# Generated by Django 5.2.5 on 2025-08-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_ingrediantsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionmodel',
            name='instruction_text',
            field=models.TextField(null=True),
        ),
    ]
